DROP TABLE member_tb;
DROP TABLE question_tb;
DROP TABLE answer_tb;
DROP TABLE report_tb;
DROP TABLE coinhistory_tb;
DROP TABLE bank_tb;


DROP SEQUENCE question_seq;
DROP SEQUENCE answer_seq;
DROP SEQUENCE report_seq;
DROP SEQUENCE coinhistory_seq;
DROP SEQUENCE bank_seq;


CREATE TABLE member_tb(
mId VARCHAR2(100) PRIMARY KEY,
mPassword VARCHAR2(20) NOT NULL,
mName VARCHAR2(20) NOT NULL,
mBalance NUMBER);


CREATE TABLE question_tb(
qId NUMBER PRIMARY KEY,
qTitle VARCHAR2(100) NOT NULL,
qContents VARCHAR2(4000) NOT NULL,
qReadCount NUMBER,
qDate DATE NOT NULL,
qChoose NUMBER,
mId VARCHAR2(100) NOT NULL);


CREATE TABLE answer_tb(
aId NUMBER PRIMARY KEY,
aContents VARCHAR2(4000) NOT NULL,
aLike NUMBER,
aChoose NUMBER,
aDate DATE NOT NULL,
qId NUMBER NOT NULL,
mId VARCHAR2(100) NOT NULL);


CREATE TABLE report_tb(
rId NUMBER PRIMARY KEY,
rContents NUMBER NOT NULL,
mId VARCHAR2(100) NOT NULL,
rAttacker VARCHAR2(100) NOT NULL,
rDate DATE NOT NULL,
rCheck NUMBER,
qId NUMBER NOT NULL,
aId NUMBER NOT NULL);


CREATE TABLE coinhistory_tb(
cId NUMBER PRIMARY KEY,
cKind NUMBER NOT NULL,
cAmount NUMBER NOT NULL,
cBalance NUMBER NOT NULL,
mId VARCHAR2(100) NOT NULL,
qId NUMBER NOT NULL);


CREATE TABLE bank_tb(
bId NUMBER PRIMARY KEY,
bName VARCHAR2(20) NOT NULL,
bNum VARCHAR2(40) NOT NULL,
bOwner VARCHAR2(20) NOT NULL,
mId VARCHAR2(100) NOT NULL);


CREATE SEQUENCE question_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE answer_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE report_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE coinhistory_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE bank_seq START WITH 1 INCREMENT BY 1;